import { useState, useEffect, useMemo, useRef } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { useHotkeys } from '@/hooks/use-hotkeys'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { DescriptionTextarea } from '@/components/ui/description-textarea'
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxEmpty,
} from '@/components/ui/combobox'
import { HugeiconsIcon } from '@hugeicons/react'
import { TaskAdd01Icon, Folder01Icon } from '@hugeicons/core-free-icons'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { useCreateTask } from '@/hooks/use-tasks'
import { useBranches, checkIsGitRepo } from '@/hooks/use-filesystem'
import { useWorktreeBasePath, useDefaultGitReposDir } from '@/hooks/use-config'
import { useRepositories, useCreateRepository } from '@/hooks/use-repositories'
import { FilesystemBrowser } from '@/components/ui/filesystem-browser'
import type { Repository } from '@/types'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function generateBranchName(text: string): string {
  // Take only the first 4 words to keep worktree paths short
  const words = text.trim().split(/\s+/).slice(0, 4).join(' ')
  const slug = slugify(words)
  if (!slug) return ''
  const suffix = Math.random().toString(36).substring(2, 6)
  return `${slug}-${suffix}`
}

interface CreateTaskModalProps {
  open?: boolean
  onOpenChange?: (open: boolean) => void
  defaultRepository?: Repository
  showTrigger?: boolean
}

export function CreateTaskModal({ open: controlledOpen, onOpenChange, defaultRepository, showTrigger = true }: CreateTaskModalProps = {}) {
  const { t } = useTranslation('tasks')
  const { t: tc } = useTranslation('common')
  const [internalOpen, setInternalOpen] = useState(false)

  // Support both controlled and uncontrolled modes
  const open = controlledOpen ?? internalOpen
  const setOpen = onOpenChange ?? setInternalOpen
  const [browserOpen, setBrowserOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [repoPath, setRepoPath] = useState('')
  const [baseBranch, setBaseBranch] = useState('')
  const [branch, setBranch] = useState('')
  const [autoGeneratedBranch, setAutoGeneratedBranch] = useState('')
  const [aiMode, setAiMode] = useState<'default' | 'plan'>('default')
  const [aiModeManuallySet, setAiModeManuallySet] = useState(false)
  const [selectedRepoId, setSelectedRepoId] = useState<string | null>(null)
  const [repoTab, setRepoTab] = useState<'saved' | 'browse'>('browse')
  const [repoSearchQuery, setRepoSearchQuery] = useState('')
  const [repoError, setRepoError] = useState<string | null>(null)
  const [isValidatingRepo, setIsValidatingRepo] = useState(false)

  const navigate = useNavigate()
  const createTask = useCreateTask()
  const createRepository = useCreateRepository()
  const formRef = useRef<HTMLFormElement>(null)
  const { data: worktreeBasePath } = useWorktreeBasePath()
  const { data: defaultGitReposDir } = useDefaultGitReposDir()
  const { data: repositories } = useRepositories()
  const { data: branchData, isLoading: branchesLoading } = useBranches(
    repoPath || null
  )

  // Get the selected repository object
  const selectedRepo = selectedRepoId ? repositories?.find((r) => r.id === selectedRepoId) : null

  // Filter repositories based on search query (case-insensitive fuzzy match)
  const filteredRepositories = useMemo(() => {
    if (!repositories) return []
    // Don't filter when a repo is selected and the query matches its display name
    // This ensures all repos are shown in the dropdown when the modal opens
    if (selectedRepo && repoSearchQuery === selectedRepo.displayName) {
      return repositories
    }
    if (!repoSearchQuery.trim()) return repositories
    const query = repoSearchQuery.toLowerCase()
    return repositories.filter((repo) =>
      repo.displayName.toLowerCase().includes(query) ||
      repo.path.toLowerCase().includes(query)
    )
  }, [repositories, repoSearchQuery, selectedRepo])

  // Set default tab based on whether repositories exist
  useEffect(() => {
    if (repositories && repositories.length > 0) {
      setRepoTab('saved')
    } else {
      setRepoTab('browse')
    }
  }, [repositories])

  // Initialize with default repository when modal opens, or auto-select most recently used
  useEffect(() => {
    if (open) {
      if (defaultRepository) {
        // Use provided default repository
        setSelectedRepoId(defaultRepository.id)
        setRepoPath(defaultRepository.path)
        setRepoSearchQuery(defaultRepository.displayName)
        setRepoTab('saved')
      } else if (repositories && repositories.length > 0) {
        // Auto-select first repository (most recently used due to sorting)
        const firstRepo = repositories[0]
        setSelectedRepoId(firstRepo.id)
        setRepoPath(firstRepo.path)
        setRepoSearchQuery(firstRepo.displayName)
        setRepoTab('saved')
      }
    }
  }, [open, defaultRepository, repositories])

  // Set default base branch when branches are loaded, reset when repo changes
  useEffect(() => {
    if (branchData) {
      setBaseBranch(branchData.defaultBranch || branchData.branches[0] || 'main')
    } else {
      setBaseBranch('')
    }
  }, [branchData, repoPath])

  const handleTitleChange = (value: string) => {
    setTitle(value)
    // Generate a new auto-generated branch name when title changes
    setAutoGeneratedBranch(generateBranchName(value))
  }

  const handleRepoSelect = async (path: string) => {
    setRepoError(null)
    setIsValidatingRepo(true)

    try {
      const result = await checkIsGitRepo(path)

      if (!result.isGitRepo) {
        setRepoError(t('createModal.errors.notGitRepo'))
        setIsValidatingRepo(false)
        return
      }

      // Valid git repo - set the path
      setRepoPath(path)

      // Check if this path matches an existing saved repository
      const existingRepo = repositories?.find((r) => r.path === path)
      if (existingRepo) {
        // Use the existing repo's settings (copyFiles, startupScript, etc.)
        setSelectedRepoId(existingRepo.id)
      } else {
        setSelectedRepoId(null)
        // Auto-add to repositories if not already saved
        const displayName = path.split('/').pop() || 'Unknown'
        createRepository.mutate({
          path,
          displayName,
        })
      }
    } catch (err) {
      setRepoError(err instanceof Error ? err.message : t('createModal.errors.validationFailed'))
    } finally {
      setIsValidatingRepo(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!title.trim() || !repoPath) return

    const repoName = repoPath.split('/').pop() || 'repo'
    // Use entered branch or auto-generated branch (which includes suffix)
    const effectiveBranch = branch.trim() || autoGeneratedBranch
    const worktreePath = `${worktreeBasePath}/${effectiveBranch}`

    createTask.mutate(
      {
        title: title.trim(),
        description: description.trim(),
        agent: selectedRepo?.agent || 'claude',
        aiMode,
        repoPath,
        repoName,
        baseBranch: baseBranch || 'main',
        branch: effectiveBranch,
        worktreePath,
        copyFiles: selectedRepo?.copyFiles || undefined,
        startupScript: selectedRepo?.startupScript || undefined,
        agentOptions: selectedRepo?.agentOptions || undefined,
      },
      {
        onSuccess: (task) => {
          const navState = description.trim()
            ? { aiMode, description: description.trim() }
            : { aiMode }
          setOpen(false)
          setTitle('')
          setDescription('')
          setRepoPath('')
          setBaseBranch('')
          setBranch('')
          setAutoGeneratedBranch('')
          setAiMode('default')
          setAiModeManuallySet(false)
          setSelectedRepoId(null)
          setRepoSearchQuery('')
          setRepoError(null)
          // Reset tab to saved if repositories exist, otherwise browse
          setRepoTab(repositories && repositories.length > 0 ? 'saved' : 'browse')
          navigate({ to: '/tasks/$taskId', params: { taskId: task.id }, state: navState as Record<string, unknown> })
        },
        onError: (error) => {
          toast.error(t('createModal.errors.createFailed'), {
            description: error instanceof Error ? error.message : String(error),
          })
        },
      }
    )
  }

  // Cmd+Enter to submit form when modal is open
  const canSubmit = !createTask.isPending && !!title.trim() && !!repoPath
  useHotkeys('meta+enter', () => {
    if (formRef.current) {
      formRef.current.requestSubmit()
    }
  }, {
    enabled: open && canSubmit,
    allowInInput: true,
    ignoreContext: true,
    deps: [open, canSubmit],
  })

  const effectiveBranch = branch.trim() || autoGeneratedBranch
  const displayWorktreePath = effectiveBranch
    ? `${worktreeBasePath}/${effectiveBranch}`
    : ''

  return (
    <>
      <Dialog open={open} onOpenChange={setOpen}>
        {showTrigger && (
          <DialogTrigger render={<Button size="sm" />}>
            <HugeiconsIcon icon={TaskAdd01Icon} size={16} strokeWidth={2} data-slot="icon" className="-translate-y-px" />
            {t('newTask')}
          </DialogTrigger>
        )}
        <DialogContent className="sm:max-w-md max-h-[80dvh] flex flex-col overflow-hidden">
          <form ref={formRef} onSubmit={handleSubmit} className="flex flex-col min-h-0 flex-1">
            <DialogHeader className="shrink-0">
              <DialogTitle>{t('createModal.title')}</DialogTitle>
              <DialogDescription>
                {t('createModal.description')}
              </DialogDescription>
            </DialogHeader>

            <FieldGroup className="mt-4 pb-4 overflow-y-auto min-h-0 flex-1">
              <Field>
                <FieldLabel htmlFor="title">{t('createModal.fields.title')}</FieldLabel>
                <Input
                  id="title"
                  value={title}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder={t('createModal.fields.titlePlaceholder')}
                  required
                />
              </Field>

              <Field>
                <FieldLabel htmlFor="description">{t('createModal.fields.description')}</FieldLabel>
                <DescriptionTextarea
                  id="description"
                  value={description}
                  onValueChange={(value) => {
                    setDescription(value)
                    // Auto-switch AI mode based on description content (unless manually set)
                    if (!aiModeManuallySet) {
                      setAiMode(value.trim() ? 'plan' : 'default')
                    }
                  }}
                  placeholder={t('createModal.fields.descriptionPlaceholder')}
                  rows={2}
                />
              </Field>

              <Field>
                <FieldLabel>{t('createModal.fields.aiMode')}</FieldLabel>
                <ToggleGroup
                  value={[aiMode]}
                  onValueChange={(value) => {
                    const selected = Array.isArray(value) ? value[0] : value
                    if (selected) {
                      setAiMode(selected as 'default' | 'plan')
                      setAiModeManuallySet(true)
                    }
                  }}
                  className="w-full"
                  variant="outline"
                >
                  <ToggleGroupItem value="plan" className="flex-1">{t('createModal.aiModes.plan')}</ToggleGroupItem>
                  <ToggleGroupItem value="default" className="flex-1">{t('createModal.aiModes.default')}</ToggleGroupItem>
                </ToggleGroup>
              </Field>

              <Field>
                <FieldLabel>{t('createModal.fields.repository')}</FieldLabel>
                <Tabs
                  value={repoTab}
                  onValueChange={(v) => {
                    setRepoTab(v as 'saved' | 'browse')
                    setRepoError(null)
                  }}
                >
                  <TabsList>
                    <TabsTrigger value="saved" disabled={!repositories?.length}>
                      {t('createModal.tabs.saved')}
                    </TabsTrigger>
                    <TabsTrigger value="browse">{t('createModal.tabs.browse')}</TabsTrigger>
                  </TabsList>

                  <TabsContent value="saved" className="mt-2">
                    <Combobox
                      value={selectedRepoId || ''}
                      onValueChange={(id) => {
                        const repo = repositories?.find((r) => r.id === id)
                        if (repo) {
                          setSelectedRepoId(id as string)
                          setRepoPath(repo.path)
                          setRepoSearchQuery(repo.displayName)
                          setRepoError(null)
                        }
                      }}
                      inputValue={repoSearchQuery}
                      onInputValueChange={(value) => {
                        setRepoSearchQuery(value)
                        // Clear selection if user starts typing something different
                        if (selectedRepo && value !== selectedRepo.displayName) {
                          setSelectedRepoId(null)
                        }
                      }}
                      itemToStringLabel={(id) =>
                        repositories?.find((r) => r.id === id)?.displayName || ''
                      }
                    >
                      <ComboboxInput
                        placeholder={t('createModal.searchRepositories')}
                        className="w-full"
                      />
                      <ComboboxContent>
                        <ComboboxList>
                          <ComboboxEmpty>{t('createModal.noRepositoriesFound')}</ComboboxEmpty>
                          {filteredRepositories.map((repo) => (
                            <ComboboxItem key={repo.id} value={repo.id}>
                              {repo.displayName}
                            </ComboboxItem>
                          ))}
                        </ComboboxList>
                      </ComboboxContent>
                    </Combobox>
                  </TabsContent>

                  <TabsContent value="browse" className="mt-2">
                    <Button
                      type="button"
                      variant="outline"
                      className="w-full justify-start font-normal"
                      onClick={() => setBrowserOpen(true)}
                      disabled={isValidatingRepo}
                    >
                      <HugeiconsIcon
                        icon={Folder01Icon}
                        size={14}
                        strokeWidth={2}
                        className="mr-2"
                      />
                      {isValidatingRepo ? (
                        <span className="text-muted-foreground">{tc('status.validating')}</span>
                      ) : repoPath && !selectedRepoId ? (
                        <span className="truncate">{repoPath}</span>
                      ) : (
                        <span className="text-muted-foreground group-hover/button:text-accent-foreground">{t('createModal.selectFolder')}</span>
                      )}
                    </Button>
                  </TabsContent>
                </Tabs>

                {repoError && (
                  <p className="text-sm text-destructive">{repoError}</p>
                )}

                {repoPath && !repoError && (
                  <FieldDescription className="font-mono text-xs truncate">
                    {repoPath}
                  </FieldDescription>
                )}
              </Field>

              <Field>
                <FieldLabel htmlFor="baseBranch">{t('createModal.fields.baseBranch')}</FieldLabel>
                <Select
                  value={baseBranch}
                  onValueChange={(value) => setBaseBranch(value ?? '')}
                  disabled={!repoPath || branchesLoading}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue>
                      {baseBranch || (
                        <span className="text-muted-foreground">
                          {!repoPath
                            ? t('createModal.selectRepositoryFirst')
                            : branchesLoading
                            ? t('createModal.loadingBranches')
                            : t('createModal.selectBranch')}
                        </span>
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {branchData?.branches.map((b) => (
                      <SelectItem key={b} value={b}>
                        {b}
                        {b === branchData.current && (
                          <span className="text-muted-foreground ml-2">{t('createModal.current')}</span>
                        )}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>

              <Field>
                <FieldLabel htmlFor="branch">{t('createModal.fields.branchName')}</FieldLabel>
                <Input
                  id="branch"
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                  placeholder={autoGeneratedBranch || t('createModal.fields.branchPlaceholder')}
                />
                {displayWorktreePath && (
                  <FieldDescription>
                    {t('createModal.worktreePrefix')} {displayWorktreePath}
                  </FieldDescription>
                )}
                {!branch.trim() && autoGeneratedBranch && (
                  <FieldDescription>
                    {t('createModal.branchAutoGenerated', { branch: autoGeneratedBranch })}
                  </FieldDescription>
                )}
              </Field>
            </FieldGroup>

            <DialogFooter className="mt-4 shrink-0">
              <DialogClose render={<Button variant="outline" type="button" className="border-destructive text-destructive hover:bg-destructive hover:text-white" />}>
                {tc('buttons.cancel')}
              </DialogClose>
              <Button
                type="submit"
                disabled={createTask.isPending || !title.trim() || !repoPath}
              >
                {createTask.isPending ? tc('status.creating') : t('createModal.createTask')}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <FilesystemBrowser
        open={browserOpen}
        onOpenChange={setBrowserOpen}
        onSelect={handleRepoSelect}
        initialPath={defaultGitReposDir || undefined}
      />
    </>
  )
}
