import { useState, useEffect } from 'react'
import { useNavigate } from '@tanstack/react-router'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { HugeiconsIcon } from '@hugeicons/react'
import { PlusSignIcon, Folder01Icon } from '@hugeicons/core-free-icons'
import { Switch } from '@/components/ui/switch'
import { useCreateTask } from '@/hooks/use-tasks'
import { useBranches } from '@/hooks/use-filesystem'
import { useWorktreeBasePath, useDefaultGitReposDir } from '@/hooks/use-config'
import { FilesystemBrowser } from '@/components/ui/filesystem-browser'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function generateBranchName(text: string): string {
  const slug = slugify(text)
  if (!slug) return ''
  const suffix = Math.random().toString(36).substring(2, 6)
  return `${slug}-${suffix}`
}

export function CreateTaskModal() {
  const [open, setOpen] = useState(false)
  const [browserOpen, setBrowserOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [repoPath, setRepoPath] = useState('')
  const [baseBranch, setBaseBranch] = useState('')
  const [branch, setBranch] = useState('')
  const [autoGeneratedBranch, setAutoGeneratedBranch] = useState('')
  const [initializeVibora, setInitializeVibora] = useState(true)

  const navigate = useNavigate()
  const createTask = useCreateTask()
  const { data: worktreeBasePath } = useWorktreeBasePath()
  const { data: defaultGitReposDir } = useDefaultGitReposDir()
  const { data: branchData, isLoading: branchesLoading } = useBranches(
    repoPath || null
  )

  // Set default base branch when branches are loaded, reset when repo changes
   
  useEffect(() => {
    if (branchData) {
      setBaseBranch(branchData.current || branchData.branches[0] || 'main')
    } else {
      setBaseBranch('')
    }
  }, [branchData, repoPath])

  const handleTitleChange = (value: string) => {
    setTitle(value)
    // Generate a new auto-generated branch name when title changes
    setAutoGeneratedBranch(generateBranchName(value))
  }

  const handleRepoSelect = (path: string) => {
    setRepoPath(path)
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!title.trim() || !repoPath) return

    const repoName = repoPath.split('/').pop() || 'repo'
    // Use entered branch or auto-generated branch (which includes suffix)
    const effectiveBranch = branch.trim() || autoGeneratedBranch
    const worktreePath = `${worktreeBasePath}/${effectiveBranch}`

    createTask.mutate(
      {
        title: title.trim(),
        description: description.trim(),
        repoPath,
        repoName,
        baseBranch: baseBranch || 'main',
        branch: effectiveBranch,
        worktreePath,
        initializeVibora,
      },
      {
        onSuccess: (task) => {
          setOpen(false)
          setTitle('')
          setDescription('')
          setRepoPath('')
          setBaseBranch('')
          setBranch('')
          setAutoGeneratedBranch('')
          setInitializeVibora(true)
          navigate({ to: '/tasks/$taskId', params: { taskId: task.id } })
        },
      }
    )
  }

  const repoName = repoPath ? repoPath.split('/').pop() : ''
  const effectiveBranch = branch.trim() || autoGeneratedBranch
  const displayWorktreePath = effectiveBranch
    ? `${worktreeBasePath}/${effectiveBranch}`
    : ''

  return (
    <>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger render={<Button size="sm" />}>
          <HugeiconsIcon icon={PlusSignIcon} size={16} strokeWidth={2} data-slot="icon" />
          New Task
        </DialogTrigger>
        <DialogContent className="sm:max-w-md">
          <form onSubmit={handleSubmit}>
            <DialogHeader>
              <DialogTitle>Create New Task</DialogTitle>
              <DialogDescription>
                Create a new task with a git worktree for isolated development.
              </DialogDescription>
            </DialogHeader>

            <FieldGroup className="mt-4">
              <Field>
                <FieldLabel htmlFor="title">Title</FieldLabel>
                <Input
                  id="title"
                  value={title}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="Add user authentication"
                  required
                />
              </Field>

              <Field>
                <FieldLabel htmlFor="description">Description</FieldLabel>
                <Textarea
                  id="description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Implement OAuth2 login flow..."
                  rows={2}
                />
              </Field>

              <Field>
                <FieldLabel>Repository</FieldLabel>
                <Button
                  type="button"
                  variant="outline"
                  className="w-full justify-start font-normal"
                  onClick={() => setBrowserOpen(true)}
                >
                  <HugeiconsIcon
                    icon={Folder01Icon}
                    size={14}
                    strokeWidth={2}
                    className="mr-2"
                  />
                  {repoName ? (
                    <span className="truncate">{repoPath}</span>
                  ) : (
                    <span className="text-muted-foreground">Select repository...</span>
                  )}
                </Button>
              </Field>

              <Field>
                <FieldLabel htmlFor="baseBranch">Base Branch</FieldLabel>
                <Select
                  value={baseBranch}
                  onValueChange={(value) => setBaseBranch(value ?? '')}
                  disabled={!repoPath || branchesLoading}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue>
                      {baseBranch || (
                        <span className="text-muted-foreground">
                          {!repoPath
                            ? 'Select repository first'
                            : branchesLoading
                            ? 'Loading branches...'
                            : 'Select branch'}
                        </span>
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {branchData?.branches.map((b) => (
                      <SelectItem key={b} value={b}>
                        {b}
                        {b === branchData.current && (
                          <span className="text-muted-foreground ml-2">(current)</span>
                        )}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>

              <Field>
                <FieldLabel htmlFor="branch">Branch Name</FieldLabel>
                <Input
                  id="branch"
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                  placeholder={autoGeneratedBranch || 'auto-generated-from-title'}
                />
                {displayWorktreePath && (
                  <FieldDescription>
                    Worktree: {displayWorktreePath}
                  </FieldDescription>
                )}
                {!branch.trim() && autoGeneratedBranch && (
                  <FieldDescription>
                    Will use "{autoGeneratedBranch}" if left empty.
                  </FieldDescription>
                )}
              </Field>

              <Field className="flex flex-row items-center justify-between">
                <div>
                  <FieldLabel htmlFor="initializeVibora" className="mb-0 cursor-pointer">
                    Initialize Vibora
                  </FieldLabel>
                  <FieldDescription>
                    Create CLAUDE.local.md with CLI instructions
                  </FieldDescription>
                </div>
                <Switch
                  id="initializeVibora"
                  checked={initializeVibora}
                  onCheckedChange={(checked) => setInitializeVibora(checked)}
                />
              </Field>
            </FieldGroup>

            <DialogFooter className="mt-4">
              <DialogClose render={<Button variant="outline" type="button" />}>
                Cancel
              </DialogClose>
              <Button
                type="submit"
                disabled={createTask.isPending || !title.trim() || !repoPath}
              >
                {createTask.isPending ? 'Creating...' : 'Create Task'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <FilesystemBrowser
        open={browserOpen}
        onOpenChange={setBrowserOpen}
        onSelect={handleRepoSelect}
        initialPath={defaultGitReposDir || undefined}
      />
    </>
  )
}
