import { useState, useEffect, useMemo } from 'react'
import { useNavigate } from '@tanstack/react-router'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxEmpty,
} from '@/components/ui/combobox'
import { HugeiconsIcon } from '@hugeicons/react'
import { PlusSignIcon, Folder01Icon } from '@hugeicons/core-free-icons'
import { Switch } from '@/components/ui/switch'
import { useCreateTask } from '@/hooks/use-tasks'
import { useBranches, checkIsGitRepo } from '@/hooks/use-filesystem'
import { useWorktreeBasePath, useDefaultGitReposDir } from '@/hooks/use-config'
import { useRepositories, useCreateRepository } from '@/hooks/use-repositories'
import { FilesystemBrowser } from '@/components/ui/filesystem-browser'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function generateBranchName(text: string): string {
  const slug = slugify(text)
  if (!slug) return ''
  const suffix = Math.random().toString(36).substring(2, 6)
  return `${slug}-${suffix}`
}

export function CreateTaskModal() {
  const [open, setOpen] = useState(false)
  const [browserOpen, setBrowserOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [repoPath, setRepoPath] = useState('')
  const [baseBranch, setBaseBranch] = useState('')
  const [branch, setBranch] = useState('')
  const [autoGeneratedBranch, setAutoGeneratedBranch] = useState('')
  const [initializeVibora, setInitializeVibora] = useState(true)
  const [planMode, setPlanMode] = useState(true)
  const [selectedRepoId, setSelectedRepoId] = useState<string | null>(null)
  const [repoTab, setRepoTab] = useState<'saved' | 'browse'>('browse')
  const [repoSearchQuery, setRepoSearchQuery] = useState('')
  const [repoError, setRepoError] = useState<string | null>(null)
  const [isValidatingRepo, setIsValidatingRepo] = useState(false)

  const navigate = useNavigate()
  const createTask = useCreateTask()
  const createRepository = useCreateRepository()
  const { data: worktreeBasePath } = useWorktreeBasePath()
  const { data: defaultGitReposDir } = useDefaultGitReposDir()
  const { data: repositories } = useRepositories()
  const { data: branchData, isLoading: branchesLoading } = useBranches(
    repoPath || null
  )

  // Get the selected repository object
  const selectedRepo = selectedRepoId ? repositories?.find((r) => r.id === selectedRepoId) : null

  // Filter repositories based on search query (case-insensitive fuzzy match)
  const filteredRepositories = useMemo(() => {
    if (!repositories) return []
    if (!repoSearchQuery.trim()) return repositories
    const query = repoSearchQuery.toLowerCase()
    return repositories.filter((repo) =>
      repo.displayName.toLowerCase().includes(query) ||
      repo.path.toLowerCase().includes(query)
    )
  }, [repositories, repoSearchQuery])

  // Set default tab based on whether repositories exist
  useEffect(() => {
    if (repositories && repositories.length > 0) {
      setRepoTab('saved')
    } else {
      setRepoTab('browse')
    }
  }, [repositories])

  // Set default base branch when branches are loaded, reset when repo changes
  useEffect(() => {
    if (branchData) {
      setBaseBranch(branchData.current || branchData.branches[0] || 'main')
    } else {
      setBaseBranch('')
    }
  }, [branchData, repoPath])

  const handleTitleChange = (value: string) => {
    setTitle(value)
    // Generate a new auto-generated branch name when title changes
    setAutoGeneratedBranch(generateBranchName(value))
  }

  const handleRepoSelect = async (path: string) => {
    setRepoError(null)
    setIsValidatingRepo(true)

    try {
      const result = await checkIsGitRepo(path)

      if (!result.isGitRepo) {
        setRepoError('Selected folder is not a git repository')
        setIsValidatingRepo(false)
        return
      }

      // Valid git repo - set the path
      setRepoPath(path)
      setSelectedRepoId(null) // Clear saved selection when browsing

      // Auto-add to repositories if not already saved
      const existingRepo = repositories?.find((r) => r.path === path)
      if (!existingRepo) {
        const displayName = path.split('/').pop() || 'Unknown'
        createRepository.mutate({
          path,
          displayName,
        })
      }
    } catch (err) {
      setRepoError(err instanceof Error ? err.message : 'Failed to validate repository')
    } finally {
      setIsValidatingRepo(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!title.trim() || !repoPath) return

    const repoName = repoPath.split('/').pop() || 'repo'
    // Use entered branch or auto-generated branch (which includes suffix)
    const effectiveBranch = branch.trim() || autoGeneratedBranch
    const worktreePath = `${worktreeBasePath}/${effectiveBranch}`

    createTask.mutate(
      {
        title: title.trim(),
        description: description.trim(),
        repoPath,
        repoName,
        baseBranch: baseBranch || 'main',
        branch: effectiveBranch,
        worktreePath,
        initializeVibora,
        copyFiles: selectedRepo?.copyFiles || undefined,
        startupScript: selectedRepo?.startupScript || undefined,
      },
      {
        onSuccess: (task) => {
          const navState = planMode && description.trim()
            ? { planMode: true, description: description.trim() }
            : undefined
          setOpen(false)
          setTitle('')
          setDescription('')
          setRepoPath('')
          setBaseBranch('')
          setBranch('')
          setAutoGeneratedBranch('')
          setInitializeVibora(true)
          setPlanMode(true)
          setSelectedRepoId(null)
          setRepoSearchQuery('')
          setRepoError(null)
          // Reset tab to saved if repositories exist, otherwise browse
          setRepoTab(repositories && repositories.length > 0 ? 'saved' : 'browse')
          navigate({ to: '/tasks/$taskId', params: { taskId: task.id }, state: navState })
        },
      }
    )
  }

  const repoName = repoPath ? repoPath.split('/').pop() : ''
  const effectiveBranch = branch.trim() || autoGeneratedBranch
  const displayWorktreePath = effectiveBranch
    ? `${worktreeBasePath}/${effectiveBranch}`
    : ''

  return (
    <>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger render={<Button size="sm" />}>
          <HugeiconsIcon icon={PlusSignIcon} size={16} strokeWidth={2} data-slot="icon" />
          New Task
        </DialogTrigger>
        <DialogContent className="sm:max-w-md">
          <form onSubmit={handleSubmit}>
            <DialogHeader>
              <DialogTitle>Create New Task</DialogTitle>
              <DialogDescription>
                Create a new task with a git worktree for isolated development.
              </DialogDescription>
            </DialogHeader>

            <FieldGroup className="mt-4">
              <Field>
                <FieldLabel htmlFor="title">Title</FieldLabel>
                <Input
                  id="title"
                  value={title}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="Add user authentication"
                  required
                />
              </Field>

              <Field>
                <FieldLabel htmlFor="description">Description</FieldLabel>
                <Textarea
                  id="description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Implement OAuth2 login flow..."
                  rows={2}
                />
              </Field>

              <Field className="flex flex-row items-center justify-between">
                <div>
                  <FieldLabel htmlFor="planMode" className="mb-0 cursor-pointer">
                    Start in Plan Mode
                  </FieldLabel>
                  <FieldDescription>
                    Launch Claude with the task title and description
                  </FieldDescription>
                </div>
                <Switch
                  id="planMode"
                  checked={planMode}
                  onCheckedChange={(checked) => setPlanMode(checked)}
                />
              </Field>

              <Field>
                <FieldLabel>Repository</FieldLabel>
                <Tabs
                  value={repoTab}
                  onValueChange={(v) => {
                    setRepoTab(v as 'saved' | 'browse')
                    setRepoError(null)
                  }}
                >
                  <TabsList>
                    <TabsTrigger value="saved" disabled={!repositories?.length}>
                      Saved
                    </TabsTrigger>
                    <TabsTrigger value="browse">Browse</TabsTrigger>
                  </TabsList>

                  <TabsContent value="saved" className="mt-2">
                    <Combobox
                      value={selectedRepoId || ''}
                      onValueChange={(id) => {
                        const repo = repositories?.find((r) => r.id === id)
                        if (repo) {
                          setSelectedRepoId(id as string)
                          setRepoPath(repo.path)
                          setRepoSearchQuery(repo.displayName)
                          setRepoError(null)
                        }
                      }}
                      inputValue={repoSearchQuery}
                      onInputValueChange={(value) => {
                        setRepoSearchQuery(value)
                        // Clear selection if user starts typing something different
                        if (selectedRepo && value !== selectedRepo.displayName) {
                          setSelectedRepoId(null)
                        }
                      }}
                      itemToStringLabel={(id) =>
                        repositories?.find((r) => r.id === id)?.displayName || ''
                      }
                    >
                      <ComboboxInput
                        placeholder="Search repositories..."
                        className="w-full"
                      />
                      <ComboboxContent>
                        <ComboboxList>
                          <ComboboxEmpty>No repositories found</ComboboxEmpty>
                          {filteredRepositories.map((repo) => (
                            <ComboboxItem key={repo.id} value={repo.id} textValue={repo.displayName}>
                              {repo.displayName}
                            </ComboboxItem>
                          ))}
                        </ComboboxList>
                      </ComboboxContent>
                    </Combobox>
                  </TabsContent>

                  <TabsContent value="browse" className="mt-2">
                    <Button
                      type="button"
                      variant="outline"
                      className="w-full justify-start font-normal"
                      onClick={() => setBrowserOpen(true)}
                      disabled={isValidatingRepo}
                    >
                      <HugeiconsIcon
                        icon={Folder01Icon}
                        size={14}
                        strokeWidth={2}
                        className="mr-2"
                      />
                      {isValidatingRepo ? (
                        <span className="text-muted-foreground">Validating...</span>
                      ) : repoPath && !selectedRepoId ? (
                        <span className="truncate">{repoPath}</span>
                      ) : (
                        <span className="text-muted-foreground">Select folder...</span>
                      )}
                    </Button>
                  </TabsContent>
                </Tabs>

                {repoError && (
                  <p className="text-sm text-destructive">{repoError}</p>
                )}

                {repoPath && !repoError && (
                  <FieldDescription className="font-mono text-xs truncate">
                    {repoPath}
                  </FieldDescription>
                )}
              </Field>

              <Field>
                <FieldLabel htmlFor="baseBranch">Base Branch</FieldLabel>
                <Select
                  value={baseBranch}
                  onValueChange={(value) => setBaseBranch(value ?? '')}
                  disabled={!repoPath || branchesLoading}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue>
                      {baseBranch || (
                        <span className="text-muted-foreground">
                          {!repoPath
                            ? 'Select repository first'
                            : branchesLoading
                            ? 'Loading branches...'
                            : 'Select branch'}
                        </span>
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {branchData?.branches.map((b) => (
                      <SelectItem key={b} value={b}>
                        {b}
                        {b === branchData.current && (
                          <span className="text-muted-foreground ml-2">(current)</span>
                        )}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>

              <Field>
                <FieldLabel htmlFor="branch">Branch Name</FieldLabel>
                <Input
                  id="branch"
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                  placeholder={autoGeneratedBranch || 'auto-generated-from-title'}
                />
                {displayWorktreePath && (
                  <FieldDescription>
                    Worktree: {displayWorktreePath}
                  </FieldDescription>
                )}
                {!branch.trim() && autoGeneratedBranch && (
                  <FieldDescription>
                    Will use "{autoGeneratedBranch}" if left empty.
                  </FieldDescription>
                )}
              </Field>

              <Field className="flex flex-row items-center justify-between">
                <div>
                  <FieldLabel htmlFor="initializeVibora" className="mb-0 cursor-pointer">
                    Initialize Vibora
                  </FieldLabel>
                  <FieldDescription>
                    Create or update CLAUDE.local.md with CLI instructions
                  </FieldDescription>
                </div>
                <Switch
                  id="initializeVibora"
                  checked={initializeVibora}
                  onCheckedChange={(checked) => setInitializeVibora(checked)}
                />
              </Field>
            </FieldGroup>

            <DialogFooter className="mt-4">
              <DialogClose render={<Button variant="outline" type="button" />}>
                Cancel
              </DialogClose>
              <Button
                type="submit"
                disabled={createTask.isPending || !title.trim() || !repoPath}
              >
                {createTask.isPending ? 'Creating...' : 'Create Task'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <FilesystemBrowser
        open={browserOpen}
        onOpenChange={setBrowserOpen}
        onSelect={handleRepoSelect}
        initialPath={defaultGitReposDir || undefined}
      />
    </>
  )
}
