/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorktreesIndexRouteImport } from './routes/worktrees/index'
import { Route as TerminalsIndexRouteImport } from './routes/terminals/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as RepositoriesRepoIdRouteImport } from './routes/repositories/$repoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorktreesIndexRoute = WorktreesIndexRouteImport.update({
  id: '/worktrees/',
  path: '/worktrees/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsIndexRoute = TerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepoIdRoute = RepositoriesRepoIdRouteImport.update({
  id: '/repositories/$repoId',
  path: '/repositories/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/terminals': typeof TerminalsIndexRoute
  '/worktrees': typeof WorktreesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/terminals': typeof TerminalsIndexRoute
  '/worktrees': typeof WorktreesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/terminals/': typeof TerminalsIndexRoute
  '/worktrees/': typeof WorktreesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repositories/$repoId'
    | '/tasks/$taskId'
    | '/repositories'
    | '/settings'
    | '/tasks'
    | '/terminals'
    | '/worktrees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/repositories/$repoId'
    | '/tasks/$taskId'
    | '/repositories'
    | '/settings'
    | '/tasks'
    | '/terminals'
    | '/worktrees'
  id:
    | '__root__'
    | '/'
    | '/repositories/$repoId'
    | '/tasks/$taskId'
    | '/repositories/'
    | '/settings/'
    | '/tasks/'
    | '/terminals/'
    | '/worktrees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepositoriesRepoIdRoute: typeof RepositoriesRepoIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TerminalsIndexRoute: typeof TerminalsIndexRoute
  WorktreesIndexRoute: typeof WorktreesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worktrees/': {
      id: '/worktrees/'
      path: '/worktrees'
      fullPath: '/worktrees'
      preLoaderRoute: typeof WorktreesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/': {
      id: '/terminals/'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repoId': {
      id: '/repositories/$repoId'
      path: '/repositories/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof RepositoriesRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepositoriesRepoIdRoute: RepositoriesRepoIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TerminalsIndexRoute: TerminalsIndexRoute,
  WorktreesIndexRoute: WorktreesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
